K : 'k'
P : 'p'
YO : 'yo'
K2tog : 'k2tog'
P2tog : 'p2tog'
K3tog : 'k3tog'
P3tog : 'p3tog'
SSK : 'ssk' | 'sl1\s*k1\s*psso'
SSP : 'ssp' | 'sl1\s*p1\s*psso'
SSSK : 'sssk' | 'sl1\s*k2tog\s*psso'
SSSP : 'sssp' | 'sl1\s*p2tog\s*psso'
S2KP2 : 's2kp2' | 'sl2\*k1\s*p2?sso'
S2PP2 : 's2pp2' | 'sl2\*p1\s*p2?sso'
M1 : 'm1' | 'make1'
M1R : 'm1r' | 'make\s*1\s* right'
M1L : 'm1l' | 'make\s*1\s*left'
SL1 : 'sl1'
SL1WYF : 'sl1wyi?f' | 'sl1\s*with\s*yarn\s*in\s*front'
KTBL : 'k1\s*tbl'
